# Generated by Django 4.1.1 on 2022-09-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=3000, verbose_name='Описание')),
                ('status', models.TextField(default='new', max_length=200, verbose_name='Статус')),
                ('deadline', models.DateTimeField(verbose_name='Дата выполнения')),
            ],
        ),
    ]
