# Generated by Django 4.1.1 on 2022-09-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='Дата выполнения'),
        ),
    ]
