# Generated by Django 4.1.1 on 2022-09-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_todo_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(default=None, null=True, verbose_name='Дата выполнения'),
        ),
    ]
