# Generated by Django 4.1.1 on 2022-09-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_todo_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='full_description',
            field=models.TextField(max_length=200, null=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(max_length=3000, verbose_name='Описание'),
        ),
    ]
