# Generated by Django 4.1.1 on 2022-09-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_todo_full_description_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='full_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Подробное описание'),
        ),
    ]
