# Generated by Django 4.1.1 on 2022-09-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_todo_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='full_description',
            field=models.TextField(max_length=200, null=True, verbose_name='Подробное описание'),
        ),
    ]
