# Generated by Django 4.1.1 on 2022-09-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_todo_deadline_alter_todo_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, default=None, verbose_name='Дата выполнения'),
        ),
    ]
