# Generated by Django 4.1.1 on 2022-09-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_todo_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.TextField(blank=True, default=None, verbose_name='Дата выполнения'),
        ),
    ]
