# Generated by Django 4.1.1 on 2022-09-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_todo_deadline_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.TextField(default='new', max_length=200, verbose_name='Статус'),
        ),
    ]
