# Generated by Django 4.1.1 on 2022-09-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_todo_deadline_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.TextField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='full_description',
            field=models.TextField(default='No description', max_length=200, verbose_name='Подробное описание'),
        ),
    ]
