# Generated by Django 4.1.1 on 2022-09-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_todo_deadline_alter_todo_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.TextField(blank=True, default='No deadline', null=True, verbose_name='Дата выполнения'),
        ),
    ]
